const ORIGIN = 'https://bewilderedduck.github.io';
const USERNAME_RE = /^[A-Za-z0-9_\-]{3,20}$/;
const ROLL_LENGTHS = [{n:6,p:0.65},{n:5,p:0.16},{n:4,p:0.09},{n:3,p:0.06},{n:2,p:0.03},{n:1,p:0.01}];
const MUTS = [{name:'catastrophic',p:0.000005},{name:'rainbow',p:0.0002},{name:'mythic',p:0.002},{name:'epic',p:0.008},{name:'neon',p:0.02},{name:'rare',p:0.05},{name:'uncommon',p:0.15},{name:'normal',p:0.769795}];
const BADGES = [
['ONE LETTER ROLL','Roll exactly one letter.','Uncommon',30],['TWO LETTER ROLL','Roll exactly two letters.','Uncommon',35],['THREE LETTER ROLL','Roll exactly three letters.','Rare',45],['FOUR LETTER ROLL','Roll exactly four letters.','Rare',60],['FIVE LETTER ROLL','Roll exactly five letters.','Epic',90],['SIX LETTER ROLL','Roll six letters.','Common',20],
['TWO LETTER WORD','Get a 2-letter English word.','Rare',75],['THREE LETTER WORD','Get a 3-letter English word.','Rare',100],['FOUR LETTER WORD','Get a 4-letter English word.','Epic',160],['FIVE LETTER WORD','Get a 5-letter English word.','Legendary',260],['SIX LETTER WORD','Get a 6-letter English word.','Mythic',450],
['DOUBLE WORD','Two adjacent valid words.','Epic',220],['WORD MIRROR','A word mirrored by another word.','Legendary',350],['WORD CHAIN','Two or more adjacent words.','Mythic',500],['VOWEL PAIR','Two vowels appear together.','Uncommon',40],['CONSONANT RUN','Four or more consonants in a row.','Rare',80],
['UNCOMMON MUTATION','Get an uncommon mutation.','Uncommon',50],['RARE MUTATION','Get a rare mutation.','Rare',100],['NEON MUTATION','Get a neon mutation.','Epic',160],['EPIC MUTATION','Get an epic mutation.','Legendary',260],['MYTHIC MUTATION','Get a mythic mutation.','Mythic',500],['RAINBOW MUTATION','Get a rainbow mutation.','Rainbow',1200],['CATASTROPHIC MUTATION','Get a catastrophic mutation.','Catastrophic',5000],['DOUBLE MUTATION','Get at least two mutated letters.','Epic',300],['MUTATION RAIN','Get three or more mutated letters.','Legendary',650],
];
const WORDS2=new Set('am an as at be by do go he if in is it me my no of oh on or ox so to up us we'.split(' '));
const WORDS3=new Set('ace app ape add and ant any are art bad bag bar bed big bit box boy bug bus can cat cow day did dog dot dry egg end eye far fat few fit fly for fun get got had has hat her him his hot how ice ill ink its jam job joy key kid law lay let lie low man map may men mix mom new not now off old one out own pay pen pet pie pig put red run sad saw say sea see she sit six sky son sun tag tea ten the tie too top toy try two use war was way who why win yes you zoo'.split(' '));
const WORDS4=new Set('able acid also area army away baby back ball band bank base bath bear beat been best bill bird blue book boom both card care case cash city club cold come cook cool core dark data date dawn deal dear deep desk done door down draw dream drop each easy edge else even ever face fact farm fast feet fell fill find fire fish five food foot four free from full game give glad goal goes gold good great hair half hall hand hard have head hear heat help here high home hope hour idea into iron jump just keep kind king know land last late lead left life like line live long look love made main make many mark meal mean meet mind more most move much must name near need next nice night none note okay once only open over page pair park part past path play plus poor post read real red? road rock room rule same save school seat seen seem sent ship shop show side sing size slow some song soon sort star stay step stop such sure take talk tall team tell than that their them then they thin this time tiny told took town tree trip true turn type upon used user very wall want warm week well went were what when where which while white whoa wide wife will wind wish with wood word work world year your zero'.split(' '));
const WORDS5=new Set('about above after again among apple beach black bring brown build carry chair class clean clear close count cover daily earth early event every extra field final first floor found front fruit green group happy house human input large laugh learn light little local magic money month music never night north other party phone place plain point power press price quick quiet right river round server short sound south space speak spend sport staff start state still story study table taken thing think those three today touch tower trade train treat trust under union until value video water where which white whole woman world write young'.split(' '));
const WORDS6=new Set('always animal answer anyone around became before better called camera change choose common create danger decide during enough family father follow friend future going ground happen health island itself letter market matter memory middle mother number office person public random recent record result school second should single system though travel unique update useful versus website wonder words'.split(' '));
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':ORIGIN,'Access-Control-Allow-Credentials':'true','Cache-Control':'no-store'}})}
function cors(){return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':ORIGIN,'Access-Control-Allow-Credentials':'true','Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Max-Age':'86400'}})}
function internalEmail(username){return username.toLowerCase()+'@letter-rng.internal'}
async function sb(env,path,opts={}){const r=await fetch(env.SUPABASE_URL+path,{...opts,headers:{apikey:env.SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,...(opts.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error((d&&d.message)||d?.error_description||d?.error||`Supabase ${r.status}`);return d}
function cookie(headers,name){const raw=headers.get('Cookie')||'';for(const p of raw.split(';')){const [k,...v]=p.trim().split('=');if(k===name)return decodeURIComponent(v.join('='))}return null}
function sessionCookie(token){return `letter_rng_session=${encodeURIComponent(token)}; Max-Age=2592000; Path=/; HttpOnly; Secure; SameSite=None`}
function clearCookie(){return 'letter_rng_session=; Max-Age=0; Path=/; HttpOnly; Secure; SameSite=None'}
async function userFromRequest(request,env){const token=cookie(request.headers,'letter_rng_session');if(!token)return null;try{const auth=await sb(env,'/auth/v1/user',{headers:{Authorization:`Bearer ${token}`}});if(!auth?.id)return null;const rows=await sb(env,`/rest/v1/profiles?id=eq.${encodeURIComponent(auth.id)}&select=*`);return {auth,profile:rows?.[0]||null}}catch{return null}}
function randInt(max){return Math.floor(Math.random()*max)}
function pickLength(){const r=Math.random();let c=0;for(const x of ROLL_LENGTHS){c+=x.p;if(r<c)return x.n}return 6}
function pickLetter(){return String.fromCharCode(65+randInt(26))}
function pickMutation(){const r=Math.random();let c=0;for(const x of MUTS){c+=x.p;if(r<c)return x.name}return 'normal'}
function wordSet(n){return n===2?WORDS2:n===3?WORDS3:n===4?WORDS4:n===5?WORDS5:n===6?WORDS6:null}
function isWord(s){return !!wordSet(s.length)?.has(s.toLowerCase())}
function patterns(letters){const s=letters.join('').toLowerCase();const hits=[];for(let n=2;n<=Math.min(6,s.length);n++){const set=wordSet(n);if(set&&set.has(s)){hits.push(`${n.toUpperCase()} LETTER WORD`);}}
if(s.length>=2&&isWord(s.slice(0,2))&&s.length>=4&&isWord(s.slice(2,4)))hits.push('DOUBLE WORD');
if(s.length>=6&&isWord(s.slice(0,3))&&isWord(s.slice(3,6))&&s.slice(0,3)===s.slice(3,6).split('').reverse().join(''))hits.push('WORD MIRROR');
for(let i=0;i<s.length-2;i++){if(isWord(s.slice(i,i+2))&&isWord(s.slice(i+2,i+4))){hits.push('WORD CHAIN');break}}
if(/[aeiou]{2}/.test(s))hits.push('VOWEL PAIR'); if(/[^aeiou]{4}/.test(s))hits.push('CONSONANT RUN'); return [...new Set(hits)]}
function mutationBadges(ms){const names=new Set(ms.filter(x=>x!=='normal').map(x=>x));const hits=[];for(const n of ['uncommon','rare','neon','epic','mythic','rainbow','catastrophic'])if(names.has(n))hits.push(n.toUpperCase()+' MUTATION');const count=ms.filter(x=>x!=='normal').length;if(count>=2)hits.push('DOUBLE MUTATION');if(count>=3)hits.push('MUTATION RAIN');return hits}
function calcPoints(rarity,letters,mutations,badgePoints){let base={Common:10,Uncommon:20,Rare:35,Epic:60,Legendary:100,Mythic:250,Rainbow:1000,Catastrophic:5000}[rarity]||10;const mut={uncommon:1,rare:2,neon:4,epic:7,mythic:15,rainbow:40,catastrophic:100,normal:0};base+=mutations.reduce((a,m)=>a+(mut[m]||0),0);base+=badgePoints;return Math.round(base)}
function rarityFromPoints(points){if(points>=5000)return'Catastrophic';if(points>=1000)return'Rainbow';if(points>=250)return'Mythic';if(points>=100)return'Legendary';if(points>=60)return'Epic';if(points>=35)return'Rare';if(points>=20)return'Uncommon';return'Common'}
async function awardBadges(env,userId,names){if(!names.length)return[];const rows=await sb(env,`/rest/v1/badges?name=in.(${names.map(n=>encodeURIComponent('"'+n+'"')).join(',')})&select=id,name,points,rarity`);const newRows=[];for(const b of rows||[]){const exists=await sb(env,`/rest/v1/user_badges?user_id=eq.${userId}&badge_id=eq.${b.id}&select=badge_id`);if(!exists?.length){await sb(env,'/rest/v1/user_badges',{method:'POST',headers:{'Content-Type':'application/json','Prefer':'return=minimal'},body:JSON.stringify({user_id:userId,badge_id:b.id})});newRows.push(b)}}return newRows}
async function register(request,env){const {username,password}=await request.json();const u=String(username||'').trim();if(!USERNAME_RE.test(u))return json({error:'Username must be 3–20 characters using letters, numbers, _ or -.'},400);if(String(password||'').length<6)return json({error:'Password must be at least 6 characters.'},400);const exists=await sb(env,`/rest/v1/profiles?username=eq.${encodeURIComponent(u)}&select=id`);if(exists?.length)return json({error:'That username is already taken.'},409);const created=await sb(env,'/auth/v1/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:internalEmail(u),password,email_confirm:true,user_metadata:{username:u}})});const logged=await sb(env,'/auth/v1/token?grant_type=password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:internalEmail(u),password})});const profile=(await sb(env,`/rest/v1/profiles?id=eq.${created.id}&select=*`))[0];return new Response(JSON.stringify({user:profile}),{status:201,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':ORIGIN,'Access-Control-Allow-Credentials':'true','Set-Cookie':sessionCookie(logged.access_token)}})}
async function login(request,env){const {username,password}=await request.json();const u=String(username||'').trim();if(!USERNAME_RE.test(u)||!password)return json({error:'Invalid username or password.'},400);try{const logged=await sb(env,'/auth/v1/token?grant_type=password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:internalEmail(u),password})});const auth=await sb(env,'/auth/v1/user',{headers:{Authorization:`Bearer ${logged.access_token}`}});const profile=(await sb(env,`/rest/v1/profiles?id=eq.${auth.id}&select=*`))[0];return new Response(JSON.stringify({user:profile}),{headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':ORIGIN,'Access-Control-Allow-Credentials':'true','Set-Cookie':sessionCookie(logged.access_token)}})}catch{return json({error:'Invalid username or password.'},401)}}
async function me(request,env){const u=await userFromRequest(request,env);if(!u)return json({user:null});return json({user:u.profile})}
async function profile(request,env){const u=await userFromRequest(request,env);if(!u)return json({error:'Unauthorized'},401);if(request.method==='PATCH'){const body=await request.json();const bio=String(body.bio??'').slice(0,240);const rows=await sb(env,`/rest/v1/profiles?id=eq.${u.profile.id}`,{method:'PATCH',headers:{'Content-Type':'application/json','Prefer':'return=representation'},body:JSON.stringify({bio})});return json({user:rows[0]})}const badges=await sb(env,`/rest/v1/user_badges?user_id=eq.${u.profile.id}&select=unlocked_at,badges(name,description,rarity,points)&order=unlocked_at.desc`);return json({user:u.profile,badges:(badges||[]).map(x=>x.badges)})}
async function history(request,env){const u=await userFromRequest(request,env);if(!u)return json({error:'Unauthorized'},401);const rolls=await sb(env,`/rest/v1/rolls?user_id=eq.${u.profile.id}&select=id,letters,roll_rarity,points,badges,created_at&order=created_at.desc&limit=25`);return json({rolls})}
async function players(request,env){const rows=await sb(env,'/rest/v1/profiles?select=username,points,rolls,best_roll,best_roll_rarity,created_at&order=points.desc&limit=100');return json({players:rows||[]})}
async function roll(request,env){const u=await userFromRequest(request,env);if(!u)return json({error:'Unauthorized'},401);const length=pickLength();const letters=Array.from({length},pickLetter);const mutations=letters.map(()=>pickMutation());const rawBadgeNames=[...patterns(letters),...mutationBadges(mutations),`${length===6?'SIX':length===5?'FIVE':length===4?'FOUR':length===3?'THREE':length===2?'TWO':'ONE'} LETTER ROLL`];let preliminary=rarityFromPoints(mutations.reduce((a,m)=>a+({normal:0,uncommon:10,rare:25,neon:50,epic:90,mythic:250,rainbow:1000,catastrophic:5000}[m]||0),0));if(mutations.includes('catastrophic'))preliminary='Catastrophic';else if(mutations.includes('rainbow'))preliminary='Rainbow';else if(mutations.includes('mythic'))preliminary='Mythic';else if(mutations.includes('epic'))preliminary='Epic';const possible=await sb(env,`/rest/v1/badges?name=in.(${rawBadgeNames.map(n=>encodeURIComponent('"'+n+'"')).join(',')})&select=name,points,rarity`);const badgePoints=(possible||[]).reduce((a,b)=>a+Number(b.points||0),0);const pts=calcPoints(preliminary,letters,mutations,badgePoints);const rarity=rarityFromPoints(pts);const awarded=await awardBadges(env,u.profile.id,rawBadgeNames);const finalPoints=calcPoints(rarity,letters,mutations,awarded.reduce((a,b)=>a+Number(b.points||0),0));const rollRow=(await sb(env,'/rest/v1/rolls',{method:'POST',headers:{'Content-Type':'application/json','Prefer':'return=representation'},body:JSON.stringify({user_id:u.profile.id,letters:letters.join(''),roll_rarity:rarity,points:finalPoints,mutations, badges:rawBadgeNames,})}))[0];const newRolls=Number(u.profile.rolls||0)+1;const newTotal=Number(u.profile.points||0)+finalPoints;const isBest=!u.profile.best_roll_points||finalPoints>Number(u.profile.best_roll_points);const patch={points:newTotal,rolls:newRolls};if(isBest)Object.assign(patch,{best_roll:letters.join(''),best_roll_points:finalPoints,best_roll_rarity:rarity});const fresh=(await sb(env,`/rest/v1/profiles?id=eq.${u.profile.id}`,{method:'PATCH',headers:{'Content-Type':'application/json','Prefer':'return=representation'},body:JSON.stringify(patch)}))[0];return json({letters:rollRow.letters.split(''),mutations,roll_rarity:rarity,points:finalPoints,badges:rawBadgeNames,new_badges:awarded.map(b=>b.name),profile:fresh})}
export default {async fetch(request,env){if(request.method==='OPTIONS')return cors();const url=new URL(request.url);try{if(url.pathname==='/api/health')return json({ok:true,service:'Letter RNG Worker',version:'1.6'});if(url.pathname==='/api/auth/register'&&request.method==='POST')return await register(request,env);if(url.pathname==='/api/auth/login'&&request.method==='POST')return await login(request,env);if(url.pathname==='/api/auth/logout'&&request.method==='POST')return new Response(JSON.stringify({ok:true}),{headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':ORIGIN,'Access-Control-Allow-Credentials':'true','Set-Cookie':clearCookie()}});if(url.pathname==='/api/auth/me'&&request.method==='GET')return await me(request,env);if(url.pathname==='/api/roll'&&request.method==='POST')return await roll(request,env);if(url.pathname==='/api/history'&&request.method==='GET')return await history(request,env);if(url.pathname==='/api/profile'&&(request.method==='GET'||request.method==='PATCH'))return await profile(request,env);if(url.pathname==='/api/players'&&request.method==='GET')return await players(request,env);return json({error:'Not found'},404)}catch(e){console.error(e);return json({error:e.message||'Server error'},500)}}}
