create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (char_length(username) between 3 and 20),
  bio text not null default '' check (char_length(bio) <= 240),
  points bigint not null default 0,
  rolls bigint not null default 0,
  best_roll text,
  best_roll_points bigint not null default 0,
  best_roll_rarity text,
  auto_roll boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.badges (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text not null,
  rarity text not null,
  points bigint not null default 0
);

create table if not exists public.user_badges (
  user_id uuid not null references public.profiles(id) on delete cascade,
  badge_id bigint not null references public.badges(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  primary key(user_id,badge_id)
);

create table if not exists public.rolls (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  letters text not null,
  roll_rarity text not null,
  points bigint not null,
  mutations jsonb not null default '[]'::jsonb,
  badges text[] not null default '{}',
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.badges enable row level security;
alter table public.user_badges enable row level security;
alter table public.rolls enable row level security;

drop policy if exists "profiles_public_read" on public.profiles;
create policy "profiles_public_read" on public.profiles for select using (true);
drop policy if exists "badges_public_read" on public.badges;
create policy "badges_public_read" on public.badges for select using (true);
drop policy if exists "user_badges_public_read" on public.user_badges;
create policy "user_badges_public_read" on public.user_badges for select using (true);
drop policy if exists "rolls_owner_read" on public.rolls;
create policy "rolls_owner_read" on public.rolls for select using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (new.id, coalesce(new.raw_user_meta_data->>'username', split_part(new.email,'@',1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

insert into public.badges(name,description,rarity,points) values
('ONE LETTER ROLL','Roll exactly one letter.','Uncommon',30),
('TWO LETTER ROLL','Roll exactly two letters.','Uncommon',35),
('THREE LETTER ROLL','Roll exactly three letters.','Rare',45),
('FOUR LETTER ROLL','Roll exactly four letters.','Rare',60),
('FIVE LETTER ROLL','Roll exactly five letters.','Epic',90),
('SIX LETTER ROLL','Roll six letters.','Common',20),
('TWO LETTER WORD','Get a 2-letter English word.','Rare',75),
('THREE LETTER WORD','Get a 3-letter English word.','Rare',100),
('FOUR LETTER WORD','Get a 4-letter English word.','Epic',160),
('FIVE LETTER WORD','Get a 5-letter English word.','Legendary',260),
('SIX LETTER WORD','Get a 6-letter English word.','Mythic',450),
('DOUBLE WORD','Two adjacent valid words.','Epic',220),
('WORD MIRROR','A word mirrored by another word.','Legendary',350),
('WORD CHAIN','Two or more adjacent words.','Mythic',500),
('VOWEL PAIR','Two vowels appear together.','Uncommon',40),
('CONSONANT RUN','Four or more consonants in a row.','Rare',80),
('UNCOMMON MUTATION','Get an uncommon mutation.','Uncommon',50),
('RARE MUTATION','Get a rare mutation.','Rare',100),
('NEON MUTATION','Get a neon mutation.','Epic',160),
('EPIC MUTATION','Get an epic mutation.','Legendary',260),
('MYTHIC MUTATION','Get a mythic mutation.','Mythic',500),
('RAINBOW MUTATION','Get a rainbow mutation.','Rainbow',1200),
('CATASTROPHIC MUTATION','Get a catastrophic mutation.','Catastrophic',5000),
('DOUBLE MUTATION','Get at least two mutated letters.','Epic',300),
('MUTATION RAIN','Get three or more mutated letters.','Legendary',650)
on conflict (name) do nothing;
